[General]
ImportPaths=E:\qt\Mosui\shared
ResourcePath=E:\qt\Mosui\Mosui.qrc
BuildDir=E:\qt\Mosui\build\Desktop_Qt_6_8_3_MSVC2022_64bit-Release

; MosuiBasic 的 C++ 类型 (MosRectangle, MosWindowAgent 等) 注册在 plugin 中,
; qmllint 可能仍有部分类型无法完全解析, 关闭以下非关键警告
DismissMessages=unresolved-type,missing-type,unqualified,missing-property,import
